### ISSUE TITLE
Different Design Matrix Combinations

### ISSUE THREAD

**Issue by s3alfisc** [s3alfisc/pyfixest#10]
For options, see [here](https://cran.r-project.org/web/packages/fixest/vignettes/multiple_estimations.html):

- [x] sw()
- [x] csw()
- [ ] fsplit

**Comment by RoyalTS** [comment]
I don't suppose `fsplit` support is still in the cards? I appreciate this is a feature whose lack can easily be hacked around, but it's a feature I use frequently in R's `fixest` and – selfishly! – it'd be neat to have feature parity.

**Comment by s3alfisc** [comment]
Hi, I might actually be able to tackle this today, it should not be too complicated! I've also caught myself at work thinking of this feature (while running separate models for app and web traffic, which I suppose is a pretty common use case 😄).

**Comment by RoyalTS** [comment]
Yeah, I split regressions every which way in R. I now I could do that with interactions – indeed, for some things that's actually the better way to do it – but for some things `fsplit` is unbeatable!

Thanks @s3alfisc. Pleasure doing business with you always! :)

**Comment by s3alfisc** [comment]
Thanks @RoyalTS =) I have opened a PR here: https://github.com/py-econometrics/pyfixest/pull/656. I think it is 95% done, I just want to take a last look at the unit tests before merging.

**Comment by s3alfisc** [comment]
And it's merged, so you can try and install from github (I've also bumped the package version to 0.23.3) 🎉
