### ISSUE TITLE
ppmlhdfe in Pyfixest

### ISSUE THREAD

**Issue by aeturrell** [s3alfisc/pyfixest#170]
First, thanks for the amazing work on Pyfixest.

I have a colleague who needs to run many, many regressions using Poisson pseudo-likelihood regression with multiple levels of fixed effects (for gravity model estimation), as in [this Stata package](https://github.com/sergiocorreia/ppmlhdfe).

I'm afraid I'm not too familiar with PPML and how different it is from regular Poisson regression, so I wondered a) whether it's possible to do this in Pyfixest as is, and b) whether adding it is on the development plan?

Thank you!

**Comment by s3alfisc** [comment]
Hi @aeturrell , thanks for the nice words and for always promoting the package! 

As a matter of fact, the algorithm implemented in the [Fepois](https://github.com/s3alfisc/pyfixest/blob/ae4656419c64e09b6df9b2ff9baa4df0d3554599/pyfixest/fepois.py#L91) method directly follows the algorithm sketched out in `pplmhdfe` - so it's already implemented and I think your colleague can start estimating his/her regression models already today =) I even (mostly) follow the naming conventions of the paper, so it should be relatively easy to map from paper to the implementation. I guess that I should note in the docs that its a 1:1 implementation of the `pplmhdfe` algo 😄 

The only caveat is that I do not yet allow for "iid" errors (see [this issue](https://github.com/s3alfisc/pyfixest/issues/169), not sure what I am doing wrong), but HC1 and CRV1 errors are well tested and match `fixest` output. One other difference to `ppmlhdfe` is that they provide a lot of options to check for separation, and `fepois` currently only provides the most basic check. 

Hope this helps! =)

**Comment by aeturrell** [comment]
This is phenomenal, absolutely brilliant. I will point them in this direction! So helpful, thank you 😊

BTW, haven't got round to it yet, but it's definitely on my list to revise the [regression page](https://aeturrell.github.io/coding-for-economists/econmt-regression.html) of Coding for Economists to streamline it and feature pyfixest.

**Comment by s3alfisc** [comment]
> BTW, haven't got round to it yet, but it's definitely on my list to revise the [regression page](https://aeturrell.github.io/coding-for-economists/econmt-regression.html) of Coding for Economists to streamline it and feature pyfixest.

Cool, I'm very much looking forward to this! Let me know if I can be of any help or if you have other feature ideas / suggestions =)
