### ISSUE TITLE
v0.10 convergence problem?

### ISSUE THREAD

**Issue by grantmcdermott** [s3alfisc/pyfixest#181]
Follow up from https://github.com/s3alfisc/pyfixest/issues/98#issuecomment-1752330082

For this benchmark I am using 3 months' worth of NYC taxi data. Click on the expansion button to see my download code (originally from R but that should be immaterial). This dataset subset is about ~45m rows, but the download should complete within two to three minutes on a fast internet connection.

<details>

<summary>Data download code</summary>

```r
options(timeout = 300)
bucket = "https://ursa-labs-taxi-data.s3.us-east-2.amazonaws.com"
for (m in sprintf("%02d", 1:3)) {
    fp = file.path(paste0("nyc-taxi/year=2012/month=", m))
    dir.create(fp, recursive = TRUE)
    try(download.file(
        paste(bucket, "2012", m, "data.parquet", sep = "/"),
        file.path(fp, "data.parquet"),
        mode = "wb"
        ), silent = TRUE)
}
```

</details>

As for the actual Python data import and PyFixest code, here it is.

```py
# %%
import duckdb
import time
from pyfixest.estimation import feols
from pyfixest.summarize import summary

# %%
nyc = duckdb.sql(
    '''
    FROM '../nyc-taxi/**/*.parquet'
    SELECT
        tip_amount, trip_distance, passenger_count,
        vendor_id, payment_type, dropoff_at,
        dayofweek(dropoff_at) AS dofw
    WHERE year = 2012 AND month <= 3
    '''
    ).df()

# %%
nyc.dtypes

# %%
## Optional: convert objects to categoricals to save memory
nyc['vendor_id'] = nyc['vendor_id'].astype('category')
nyc['payment_type'] = nyc['payment_type'].astype('category')
nyc.dtypes

# %%
tic = time.time()
feols_reg = feols(
    fml = "tip_amount ~ trip_distance + passenger_count | dofw + vendor_id + payment_type", 
    data = nyc, vcov = "iid"
)
toc = time.time() - tic

```

If you're anything like me, you'll get stuck at the `feols` section. It just runs for ages (>30min) without finishing. Again, the above code was working until the 0.10 update, albeit quite slowly. I also get a `omp_set_nested` deprecation warning (superseded by `omp_set_max_active_levels`), but I think that is unrelated.

Again, please don't hesitate to point out any dumb things I might be doing above.

Thanks!
G

For posterity, here's the equivalent R code, which is working fine. 

```r
library(duckdb)
library(fixest)

con = dbConnect(duckdb()) 

nyc = dbGetQuery(
   con, 
   "
   FROM 'nyc-taxi/**/*.parquet'
   SELECT
      tip_amount, trip_distance, passenger_count,
      vendor_id, payment_type, dropoff_at,
      dayofweek(dropoff_at) AS dofw
   WHERE year = 2012 AND month <= 3
   "
)

dbDisconnect(con); rm(con)

tic = Sys.time()
feols_reg = feols(
     tip_amount ~ trip_distance + passenger_count | dofw + vendor_id + payment_type,
     data = nyc, vcov = "iid"
 )
(toc = Sys.time() - tic)
# Time difference of 13.69745 secs
```

**Comment by s3alfisc** [comment]
Thanks Grant! I just replicated your benchmarks. 15 min+ on my laptop. v0.10 came with some changes to the pre-processing & the demeaning algo. I did not have much time to look into this today, unfortunately. Hopefully tomorrow =)

**Comment by grantmcdermott** [comment]
All good, bud. No rush on my side.

**Comment by s3alfisc** [comment]
Something fishy is happening with column types: if I map to np types, I can run the full model in around 2:30 minutes. 

```python
nyc['vendor_id'] = nyc['vendor_id'].astype('category')
nyc['payment_type'] = nyc['payment_type'].astype('category')
nyc['passenger_count'] = nyc['passenger_count'].astype(np.int64)
nyc['tip_amount'] = nyc['tip_amount'].astype(np.float64)
nyc['trip_distance'] = nyc['trip_distance'].astype(np.float64)
nyc['passenger_count'] = nyc['passenger_count'].astype(np.int64)
```
Beyond, the code spends quite a bit of time initiating the `pyhdfe.algorithm`. If I skip this (as it is only used to drop singletons, which does not seem relevant in this example) and use the same convergence crit as `pyhdfe`, i.e. 

```python
@nb.njit
def _sad_converged(a, b, tol):
    for i in range(a.size):
        if np.abs(a[i] - b[i]) >= tol:
            return False
    return True
```
I can estimate the model on all 42Mio observations in around 1 minute.

**Comment by s3alfisc** [comment]
I have just released version 0.10.4 to PyPi. I've solved the convergence issue by internally converting all columns of X and Y 64-bit integers or floats. Thanks for reporting this! After some other optimizations, your nyc taxi example now runs in about 20 seconds on my laptio =)

**Comment by grantmcdermott** [comment]
Huzzah! 

A little closer to double that on my test laptop, but a great improvement all round. Thanks Alex and congrats on fixing the main bottlenecks.

**Comment by aeturrell** [comment]
Know I'm late to the party, but this is super!
