### ISSUE TITLE
Comparing multiple models without stepwise estimation

### ISSUE THREAD

**Issue by aeturrell** [s3alfisc/pyfixest#196]
Hello!

Thanks again for all your hard work on this.

I'm reproducing the exercises on the Coding for Economists' [regression page](https://aeturrell.github.io/coding-for-economists/econmt-regression.html) using Pyfixest. I'm onto the section on multiple regression, and I was wondering if there's an equivalent command to the Stargazer one used [here](https://aeturrell.github.io/coding-for-economists/econmt-regression.html#multiple-regression-models)? 

I think it could be done with stepwise regression too, but there may be use cases where stepwise doesn't work or is not how the logic of the analysis is organised. Both [Stargazer](https://github.com/StatsReporting/stargazer) and R's [modelsummary](https://modelsummary.com/articles/modelsummary.html) are good to look at for prior art on this.

**Comment by s3alfisc** [comment]
Hi Arthur, super cool that you have started to integrate Pyfixest into Coding for Economists! 

So far, the closest thing pyfixest provides is the `summary()` function, which allows to print multiple models on top of each other, which is not really great (but I considered good enough in the moment).  

```py
from pyfixest.summarize import summary
summary([model1, model2])
```
I have allocated some time this weekend to push on new pyfixest features, so I will try to produce something close to `stargazer` of `fixest::etable()`=)

**Comment by aeturrell** [comment]
Amazing, thank you for looking at this. From my POV, the dream is to recommend a single regression package to rule them all because it will make life much easier for economists new to coding so I'm only too excited to be adding it.

As I'm going through the chapter, I am likely to come up with a few more issues—just want to give you a heads up, and to say please don't feel obliged in any way to tackle them all really quickly, grateful for whatever progress you make.

**Comment by s3alfisc** [comment]
Hi, I have added a prototype implementation of `etable()` in #201 . Will merge and release after CI checks pass. It can output markdown, a `pd.DataFrame` and even latex =) 

```py
%load_ext autoreload
%autoreload 2

from pyfixest.estimation import feols
from pyfixest.utils import get_data
from pyfixest.summarize import etable
import pandas as pd

data = get_data()
fit1 = feols("Y ~ X1", data = data)
fit2 = feols("Y ~ X1 + X2", data = data)
fit3 = feols("Y ~ X2", data = data)

etable([fit1, fit2, fit3])

# | Coefficient   | est1            | est2             | est3             |
# |:--------------|:----------------|:-----------------|:-----------------|
# | Intercept     | 2.349*** (0.09) | 2.35*** (0.09)   | 2.587*** (0.056) |
# | X1            | 0.221** (0.069) | 0.228** (0.068)  |                  |
# | X2            |                 | 0.071*** (0.018) | 0.069*** (0.018) |
# Significance levels: * p < 0.05, ** p < 0.01, *** p < 0.001
```
The implementation is still rather bare bone - I could print out lots more information + make the output prettier, so I will keep this PR open even after merging.

**Comment by aeturrell** [comment]
This looks so good, thanks for kicking it off!! Happy to feedback on what a more polished version would look like but reckon the [fixest etable](https://lrberge.github.io/fixest/reference/etable.html) is a great place to start.

**Comment by s3alfisc** [comment]
I've now managed to make things a little prettier + add some information : 

```py
%load_ext autoreload
%autoreload 2

from pyfixest.estimation import feols
from pyfixest.summarize import etable
from pyfixest.utils import get_data

data = get_data()

fit1 = feols("Y ~ X1 ", data=data)
fit2 = feols("np.log(Y) ~ X1 + X2 | f2 + f1 ", data=data, vcov = {"CRV1":"f1+f2"})
fit3 = feols("Y2 ~ X1 + X2 + C(f3) | f1", data=data)

etable([fit1, fit2, fit3])

# est1              est2            est3
# -------------  ----------------  ----------------  --------------
#   depvar                        Y         np.log(Y)              Y2
# -----------------------------------------------------------------
#   Intercept      2.197*** (0.088)
# X1             0.367*** (0.068)  0.133*** (0.029)   0.491 (0.244)
# X2                               0.027*** (0.005)   0.067 (0.041)
# C(f3)[T.1.0]                                        1.221 (0.998)
# C(f3)[T.2.0]                                        0.346 (0.947)
# C(f3)[T.3.0]                                        0.856 (0.865)
# C(f3)[T.4.0]                                          0.75 (0.94)
# C(f3)[T.5.0]                                        0.705 (0.975)
# C(f3)[T.6.0]                                         0.473 (1.04)
# C(f3)[T.7.0]                                       -0.502 (1.013)
# C(f3)[T.8.0]                                       -1.082 (0.783)
# C(f3)[T.9.0]                                        0.175 (0.793)
# C(f3)[T.10.0]                                       0.828 (0.928)
# C(f3)[T.11.0]                                      -0.663 (0.609)
# C(f3)[T.12.0]                                        0.328 (1.02)
# -----------------------------------------------------------------
#   f1                            -                 x               x
# f2                            -                 x               -
#   -----------------------------------------------------------------
#   Observations                998               923             998
# S.E. type                   iid         by: f1+f2          by: f1
# -----------------------------------------------------------------
#   Significance levels: * p < 0.05, ** p < 0.01, *** p < 0.001
```
I'll close the issue with #210 for now - I will add R-squared later (I worry there might be an error in the implementation). 

Best, Alex
