### ISSUE TITLE
Enhancing _detect_singletons

### ISSUE THREAD

**Issue by styfenschaer** [s3alfisc/pyfixest#229]
Hi @s3alfisc 

I wanted to have a look at the singleton detection to speed it up possibly. You implemented that in commit 4eaef7d. May I ask why you always break in the inner loop (see code below)? Having for example such an array, you do not detect the 3rd row as a singleton :
```python
ids = np.array(
    [
        [0, 2, 1],
        [0, 2, 1],
        [0, 1, 3],
        [0, 1, 2],
        [0, 1, 2],
    ]
)
```
Probably I misunderstand the idea of singletons.

<details>
<summary>Source</summary>

```python
def _detect_singletons(ids):
    """
    Detect singleton fixed effects
    Args:have a
        ids (np.ndarray): A numpy array of fixed effects.
    Returns:
        An array of booleans indicating which observations have a singleton fixed effect.
    """

    N, k = ids.shape

    singleton_idx = np.full(N, False, dtype=bool)
    singleton_idx_tmp = np.full(N, False, dtype=bool)
    singleton_idx_tmp_old = singleton_idx.copy()

    ids_tmp = ids.copy()

    while True:
        for x in range(k):
            col = ids[:, x]
            col_tmp = ids_tmp[:, x]

            # note that this only "works" as fixed effects are integers from 0, 1, ..., n_fixef -1
            # and np.bincount orders results in ascending (integer) order
            counts = np.bincount(col_tmp)

            if np.any(counts == 1):
                idx = np.where(counts == 1)

                singleton_idx[np.isin(col, idx)] = True
                singleton_idx_tmp[np.isin(col_tmp, idx)] = True

                ids_tmp = ids_tmp[~singleton_idx_tmp, :].astype(ids_tmp.dtype)
                singleton_idx_tmp = singleton_idx_tmp[~singleton_idx_tmp]

            break

        if np.array_equal(singleton_idx_tmp, singleton_idx_tmp_old):
            break

        singleton_idx_tmp_old = singleton_idx_tmp.copy()

    return singleton_idx
```

</details>

**Comment by s3alfisc** [comment]
Hi @styfenschaer - super cool that you're taking a look at this! Here's an attempt at a quick response before one last lavish Christmas dinner 😄

I think your understanding of what a singleton group is is pretty accurate - the column  [0, 1, 3] should indeed be dropped in the example data set you provide, and what you found is really a bug! My idea probably was that as soon as we find a singleton entry in a column, we can drop the associated row from `ids` and iterate on the "reduced" array. I.e. if the array was 

```py
ids = np.array(
    [
        [0, 2, 1],
        [0, 2, 1],
        [3, 1, 3],
        [0, 1, 2],
        [0, 1, 2],
    ]
)
```
we would already find the single entry `3` in the second column for iteration `k=0` and would not have to evaluate `k = 1` and `k = 2`, but instead start all over with `k = 0` on the reduced ids array 

```py
ids = np.array(
    [
        [0, 2, 1],
        [0, 2, 1],
        [0, 1, 2],
        [0, 1, 2],
    ]
)
``` 

As far as I am aware, the best reference on the consequences of singleton fixed effects is this [short note by Correia](http://scorreia.com/research/singletons.pdf). `fixest` does not drop them by default, which is what `pyfixest` emulates, but other regression packages do (e.g. `reghdfe`).

Btw, I think there is a [bug ](https://github.com/s3alfisc/pyfixest/issues/192) in how `_detect_singletons` is currently used when users opt to do so - I plan to fix this before the new year =) 

Best, Alex
