### ISSUE TITLE
Support Polars

### ISSUE THREAD

**Issue by vincentarelbundock** [s3alfisc/pyfixest#232]
It would be neat to support Polars out of the box. 

Probably don't need to change much under the hood. Just check if user input for `data` a Pandas. If it is not, try to import Polars and call `pl.from_pandas()` if it is available (raise an `ImportError` if not available).

**Comment by s3alfisc** [comment]
Yes, thanks for the suggestion. I had not implemented it yet because I thought it would require to make polars a hard dependency, but as you correctly suggest I can solve this with a try-except statement. I'll implement this tomorrow!

**Comment by vincentarelbundock** [comment]
Yay!

**Comment by s3alfisc** [comment]
Hi @vincentarelbundock , `polars` should now be supported for `feols()` and `fepois()` `data` input arg =)

```py
from pyfixest.estimation import feols, fepois
from pyfixest.utils import get_data
import polars as pl

data = get_data()
data_pl = pl.from_pandas(data)
fit = feols("Y ~ X1", data=data)

fit.tidy()

#	Estimate	Std. Error	t value	Pr(>|t|)	2.5 %	97.5 %
# Coefficient						
# Intercept	2.230321	0.088980	25.065381	0.000000	2.055711	2.404931
# X1	0.333686	0.069076	4.830700	0.000002	0.198135	0.469238
```

**Comment by vincentarelbundock** [comment]
love it.

**Comment by vincentarelbundock** [comment]
sorry, one question since I can't test now: This works in `fit.predict()` too?

**Comment by s3alfisc** [comment]
Ah, no; I'll update this quickly.

**Comment by s3alfisc** [comment]
Support for `predict()` is added with #241 =)
