### ISSUE TITLE
Issue with `predict` when dropping collinear covariates on new data

### ISSUE THREAD

**Issue by jiafengkevinchen** [s3alfisc/pyfixest#245]
In here,
https://github.com/s3alfisc/pyfixest/blob/726037b8e9f9fa9f879bcdeb1bd0e4f44f5f8277/pyfixest/feols.py#L899C1-L904C38

I think it could be the case that `model_matrix(fml_linear, newdata)` drops some collinear columns in the new data. In this case, self._coefnames and the columns of `X` no longer line up. A "fix" is to just use the coefnames that are in new X, but I think this does not always produce expected behavior. 
```
 if not self._X_is_empty:
    # deal with linear part
    # TODO: edited this
    _, X = model_matrix(fml_linear, newdata)
    idx = np.isin(self._coefnames, X.columns)
    X = X[np.array(self._coefnames)[idx]]
    X = X.to_numpy()
    y_hat = X @ _beta_hat[idx]
```

**Comment by s3alfisc** [comment]
Thanks for raising this! 

I think in the current implementation, this should not be a problem, as the design matrix `X` produced by 

```py
    _, X = model_matrix(fml_linear, newdata)
```
should be identical to the design matrix whose cross product is checked in `_find_collinear_variables()`. Or, in other words, all covariates in `self._coefnames`should also be included in `X`.

Hence the features dropped from the fitted model are also dropped from the prediction - at least this is how I would think about predicted behavior (?) . Do you agree with this or am I missing something?

**Comment by s3alfisc** [comment]
But there is indeed something really off now, because predictions with fixed effects seem to fail: 

```py
# load autoreload 2
%load_ext autoreload
%autoreload 2

from pyfixest.estimation import feols
from pyfixest.utils import get_data
data = get_data()

fit = feols("Y ~ X1 + X2 | f1 ", data=data)
res = fit.predict(newdata = data)
res
```

**Comment by jiafengkevinchen** [comment]
Interesting, the issue is not as simple as I thought. I only get an error when I use `C(.)` to make dummies in the formula. Here's a minimal example:
```
df = pd.DataFrame({"y": np.random.randn(1000), "x": np.random.randint(124, size=1000)})
feols("y ~ C(x)", df).predict(df.query("x == 1 or x == 2 or x == 3").copy())

# KeyError: "['C(x)[T.1]', 'C(x)[T.4]', 'C(x)[T.5]', 'C(x)[T.6]', 'C(x)[T.7]', 'C(x)[T.8]', 'C(x)[T.9]', 'C(x)[T.10]', 'C(x)[T.11]', 'C(x)[T.12]', 'C(x)[T.13]', 'C(x)[T.14]', 'C(x)[T.15]', 'C(x)[T.16]', 'C(x)[T.17]', 'C(x)[T.18]', 'C(x)[T.19]', 'C(x)[T.20]', 'C(x)[T.21]', 'C(x)[T.22]', 'C(x)[T.23]', 'C(x)[T.24]', 'C(x)[T.25]', 'C(x)[T.26]', 'C(x)[T.27]', 'C(x)[T.28]', 'C(x)[T.29]', 'C(x)[T.30]', 'C(x)[T.31]', 'C(x)[T.32]', 'C(x)[T.33]', 'C(x)[T.34]', 'C(x)[T.35]', 'C(x)[T.36]', 'C(x)[T.37]', 'C(x)[T.38]', 'C(x)[T.39]', 'C(x)[T.40]', 'C(x)[T.41]', 'C(x)[T.42]', 'C(x)[T.43]', 'C(x)[T.44]', 'C(x)[T.45]', 'C(x)[T.46]', 'C(x)[T.47]', 'C(x)[T.48]', 'C(x)[T.49]', 'C(x)[T.50]', 'C(x)[T.51]', 'C(x)[T.52]', 'C(x)[T.53]', 'C(x)[T.54]', 'C(x)[T.55]', 'C(x)[T.56]', 'C(x)[T.57]', 'C(x)[T.58]', 'C(x)[T.59]', 'C(x)[T.60]', 'C(x)[T.61]', 'C(x)[T.62]', 'C(x)[T.63]', 'C(x)[T.64]', 'C(x)[T.65]', 'C(x)[T.66]', 'C(x)[T.67]', 'C(x)[T.68]', 'C(x)[T.69]', 'C(x)[T.70]', 'C(x)[T.71]', 'C(x)[T.72]', 'C(x)[T.73]', 'C(x)[T.74]', 'C(x)[T.75]', 'C(x)[T.76]', 'C(x)[T.77]', 'C(x)[T.78]', 'C(x)[T.79]', 'C(x)[T.80]', 'C(x)[T.81]', 'C(x)[T.82]', 'C(x)[T.83]', 'C(x)[T.84]', 'C(x)[T.85]', 'C(x)[T.86]', 'C(x)[T.87]', 'C(x)[T.88]', 'C(x)[T.89]', 'C(x)[T.90]', 'C(x)[T.91]', 'C(x)[T.92]', 'C(x)[T.93]', 'C(x)[T.94]', 'C(x)[T.95]', 'C(x)[T.96]', 'C(x)[T.97]', 'C(x)[T.98]', 'C(x)[T.99]', 'C(x)[T.100]', 'C(x)[T.101]', 'C(x)[T.102]', 'C(x)[T.103]', 'C(x)[T.104]', 'C(x)[T.105]', 'C(x)[T.106]', 'C(x)[T.107]', 'C(x)[T.108]', 'C(x)[T.109]', 'C(x)[T.110]', 'C(x)[T.111]', 'C(x)[T.112]', 'C(x)[T.113]', 'C(x)[T.114]', 'C(x)[T.115]', 'C(x)[T.116]', 'C(x)[T.117]', 'C(x)[T.118]', 'C(x)[T.119]', 'C(x)[T.120]', 'C(x)[T.121]', 'C(x)[T.122]', 'C(x)[T.123]'] not in index"
```

**Comment by s3alfisc** [comment]
Ah yes, I see! Thank you! There's a lot of code in `predict()` and `fixef()` to handle this case for "proper" fixed effects that are swiped out in the estimation. Basically, if a fixed effect level was present in the estimation data but is not in `newdata`, `predict() / fixef()` check this and set `_sumFE` to `np.nan`. 

Though I think your proposal above should be able to handle this case - what are the undesired side effects you had in mind? If not too severe, would you be up to set up a PR? =) (Though I'd be happy to do it myself in case you don't have the time / don't want to for any other reasons).

**Comment by s3alfisc** [comment]
Not too surprisingly, `fixest` gets this right: 

```r
library(fixest)
library(reticulate)

df = py$df
fml = y ~ as.factor(x)
fit = feols(fml, data = df)

predict(fit, df[df$x %in% c(1, 2, 3), ])
#[1] -0.2653724 -0.2653724 -0.4016452 -0.4016452 -0.2653724 -0.4016452
```

**Comment by jiafengkevinchen** [comment]
Yeah, my proposal should work if all the missing columns are meant to be all zeros, which is certainly true if this bug is only caused by `C(.)`. I wasn't sure what other situations might cause this. 

I would be more comfortable if you could set up the PR :). Thanks for the package by the way!

**Comment by s3alfisc** [comment]
> I would be more comfortable if you could set up the PR :). 

Sure thing, I have set up the PR and will merge after unit tests pass =) 

> Thanks for the package by the way!

It's my pleasure! Thanks for taking a close look at the code and reporting all these bugs, it's been super valuable =)
