### ISSUE TITLE
Move docs to `quartodoc`, generally improve documentation and fix docstrings

### ISSUE THREAD

**Issue by s3alfisc** [s3alfisc/pyfixest#257]

**Comment by NKeleher** [comment]
@s3alfisc  - Really grateful for all of the effort you've put into `pyfixest`. It's a much-appreciated contribution to the Python econometrics/DS toolkit.

I'm wondering if this might be a good first issue for me to help out with. Digging into the docs would help familiarize me with the backend.

Looks like you might have done much of the migration to `quartodoc` in https://github.com/s3alfisc/pyfixest/pull/264. :tada: 

Is there additional docs support that you'd like to prioritize?

**Comment by s3alfisc** [comment]
Hi @NKeleher, it's socool that you're reaching out! And thanks for the nice words =)

I have indeed migrated the documentation to `quartodoc` and improved it a little bit. The docs look much nicer now, but their information content is still far from perfect. There are some small gaps all over the place - for example for the [`vcov` argument](https://s3alfisc.github.io/pyfixest/reference/estimation.feols.html#pyfixest.estimation.feols) to `feols()`, the docs state "Type of variance-covariance matrix for inference. Options include “iid”, “hetero”, “HC1”, “HC2”, “HC3”, or a dictionary for CRV1/CRV3 inference." The description does not mention any defaults (which are just the fixest defaults) nor is it really clear from the documentation how users have to pass the dictionary for CRV inference. There's also no mention of two-way clustering, etc. So in general, there is a lot of potential to improve the documentation! 

And besides, I still struggle with quartodoc a little bit, for example, [the starting page ](https://s3alfisc.github.io/pyfixest/) somehow points to the difference-in-differences vignette 😕 

If you want to start looking at the codebase, the best starting point would be [pyfixest.estimation.feols](https://github.com/s3alfisc/pyfixest/blob/4533dc25e6a7e180a837c8cad93cbe91684cbdd3/pyfixest/estimation.py#L12) and then to follow it through the codebase to the [FixestMulti](https://github.com/s3alfisc/pyfixest/blob/master/pyfixest/FixestMulti.py#L19) class, which first deparses the formula string in [FixestFormulaParser](https://github.com/s3alfisc/pyfixest/blob/master/pyfixest/FormulaParser.py#L11) (you might want to skip this in the beginning, as it is not very pretty code 😅 ).  From there, you more or less get a dictionary with formula strings, which `FixestMulti._estimate_all_models` loops over. In general, this is the key method where most of the action happens: the creation of the model matrix via [model_matrix_fixest](https://github.com/s3alfisc/pyfixest/blob/master/pyfixest/model_matrix_fixest.py#L12), the demeaning (and caching) of variables by the fixed effects via [demean_all_models](https://github.com/s3alfisc/pyfixest/blob/master/pyfixest/demean.py#L9), and finally estimation via the `Feols`, `Feiv` or `Fepois` classes. 

I am still not sure if this code flow is the best possible design, so if you are super confused after looking at the codebase, that would be very valuable information for me =D 

If you'd like to start working with a more "econometric" contribution, I have at some point set up a [skeleton method for Wald / F Tests ](https://github.com/s3alfisc/pyfixest/blob/4533dc25e6a7e180a837c8cad93cbe91684cbdd3/pyfixest/feols.py#L637) that still needs to be finalised & tested, or you could implement adjusted R2 values [here](https://github.com/s3alfisc/pyfixest/blob/4533dc25e6a7e180a837c8cad93cbe91684cbdd3/pyfixest/feols.py#L1185). Or even more ambitious, rewrite the [Feiv class](https://github.com/s3alfisc/pyfixest/blob/master/pyfixest/feiv.py) from a 1-step to a 2-step estimator so that it becomes feasible to support IV diagnostics. 

Anyways, thanks so much for reaching out! 

Best, Alex
