### ISSUE TITLE
Setup gh-action to build docs from `docs/_site`

### ISSUE THREAD

**Issue by s3alfisc** [s3alfisc/pyfixest#295]
Quartodoc puts all files for the site build into `docs/_site`, but gh-actions can only read from `docs`, so I currently always copy the content of `docs/_site` manually into `docs`. A gh-action like [this one ](https://github.com/peaceiris/actions-gh-pages) would of course be much more convenient =)

**Comment by NKeleher** [comment]
This is a great idea. I recently implemented this with statsframe (very-pre-alpha package) https://github.com/NKeleher/statsframe/blob/main/.github/workflows/ci.yml and heavily influenced by the pins-python workflow: https://github.com/rstudio/pins-python/blob/main/.github/workflows/ci.yml.

Do you have a dependency graph in mind, i.e. "Build tests" >> "Build docs" >> "Publish docs" on merge to main?

**Comment by s3alfisc** [comment]
> Do you have a dependency graph in mind, i.e. "Build tests" >> "Build docs" >> "Publish docs" on merge to main?
This dependency graph graph makes excellent sense to me =)

**Comment by NKeleher** [comment]
Perfect, I'll submit a PR with some suggestions on the ci workflow.

**Comment by s3alfisc** [comment]
Amazing, thank you!
