### ISSUE TITLE
Add coefstat = "tstat" option to `etable()`

### ISSUE THREAD

**Issue by christophscheuch** [s3alfisc/pyfixest#298]
Thank you so much for your work on this package, I'm a big fan already 🙏 

We are thinking about migrating our fixed effects regressions from `linearmodels` to `pyfixest` in our book [Tidy Finance with Python](https://www.tidy-finance.org/python/fixed-effects-and-clustered-standard-errors.html) to be in sync with the R version of our project (where we use `fixest`), but we'd need to print t-statistics in regression outputs with `etable()`.  

For instance, this would be great:
```
from pyfixest.estimation import feols
from pyfixest.utils import get_data
from pyfixest.summarize import etable

data = get_data()
fit = feols("Y + Y2 ~X1 | csw0(f1, f2)", data = data, vcov = {'CRV1':'group_id'})
etable([fit.fetch_model(i) for i in range(6)], coefstat="tstat")
```

**Comment by christophscheuch** [comment]
Great news, thank you @Wenzhi-Ding 🚀

**Comment by koan14** [comment]
pyfixest is fantastic! I may be missing something but is it possible to show adjusted rsquare in etable results? Thank you

**Comment by s3alfisc** [comment]
Thank you! =) yes, that's possible, you'd have to use the "custom_model_stats" argument, see here: https://py-econometrics.github.io/pyfixest/table-layout.html#further-custom-model-information
The r2 values are stored in the Feols object as "Feols._r2" attribute if I recall correctly. (Am away from keyboard atm else I would have posted a fully reproducible example).

**Comment by s3alfisc** [comment]
Edit: as you're asking about adjusted r2, it should be "Feols._r2_adjusted".

**Comment by koan14** [comment]
Thank you for responding so quickly. I'm having problems accessing  r2_adjusted.. Seems like I'm missing something. I'm trying to add adjusted rsquare for the model below. Any other suggestions would be appreciated. Thanks
import pyfixest as fe
model = fe.feols("y  ~ M + yr_0_5 + yr_5_10 + yr_10_15 + yr_15_20 ", df)
fe.etable(model)

**Comment by Wenzhi-Ding** [comment]
Current solution seems to be a little bit awkward for presenting adjusted R2. First we load sample data:

```python
import pyfixest as pf

df = pf.get_data()
```

If you only have one model, you can do:

```python
model = pf.feols("Y ~ X1 | group_id", df)
pf.etable(model, custom_model_stats={"Adjusted R2": [f'{model._r2_adj_within:.3f}']})
```

If you have multiple models:

```python
model1 = pf.feols("Y ~ X1 | group_id", df)
model2 = pf.feols("Y ~ X2 | group_id", df)
model3 = pf.feols("Y ~ Z1 | group_id", df)
model4 = pf.feols("Y ~ Z2 | group_id", df)

mdls= [model1, model2, model3, model4]
pf.etable(mdls, custom_model_stats={"Adjusted R2": [f'{x._r2_adj_within:.3f}' for x in mdls]})
```

But I found that currently only when you estimate fixed effects model we calculate adjusted R2. If no fixed effects, you can only report within R2:

```python
model = pf.feols("Y ~ X1", df)
pf.etable(model, custom_model_stats={"Within R2": [f'{model._r2_within:.3f}']})
```

---

@s3alfisc Is this something going to fix?

https://github.com/py-econometrics/pyfixest/blob/cb31ee2bf5610faa7b815acf719cd48975823756/pyfixest/estimation/feols_.py#L1896-L1908

By the way, it seems that both `Feols._adj_r2_within` and `Feols._r2_adj_within`  are defined. Maybe this is a typo?

**Comment by s3alfisc** [comment]
Hi @Wenzhi-Ding , indeed multiple things you have discovered there 😅 All things we should fix, I will open a few issues. Thanks!

**Comment by koan14** [comment]
Will double check my code. Thanks again
