### ISSUE TITLE
Make API easier to call

### ISSUE THREAD

**Issue by Wenzhi-Ding** [s3alfisc/pyfixest#329]
Currently, importing functions require multiple line of import statement at the front of the script like

```python
from pyfixest.estimation import feols
from pyfixest.summarize import etable
from pyfixest.utils import get_data
from pyfixest.visualize import coefplot
```

It increases a bit the difficulties of using this package. When I need to import one more function, I need to go back to the front and modify the import statement, and then go back to my working cell.

My suggestion is that on top of current API, we can make most common used functions easier to call, with less level of chaining (`Pandas` style)

```python
import pyfixest as pf

data = pf.get_data()
fit = pf.feols("Y ~ X", data)
pf.etable(fit)
pf.coefplot(fit)
```

We just add one more user-friendly interface, which will not affect the original way of importing functions, so existing scripts still work. If you think this is fine, I can also take on this.

**Comment by s3alfisc** [comment]
I'd love that and would 100% accept such a PR! I also regularly feel like I have to type too much... 😀

**Comment by Wenzhi-Ding** [comment]
> I'd love that and would 100% accept such a PR! I also regularly feel like I have to type too much... 😀

Hi Alex, when I sort out the code, I feel like it is time to organize each files under sub-modules, as this project becomes more comprehensive. So as a first attempt, I made a major restructing, but which may require existing scripts to be modified a bit to accomodate the new import structure. I don't know whether it makes sense to you.

Since so many files have been changed (for each file the changes are import statement rather than functions), I think it is necessary to discuss with you before PR to see whether it is fine to change. You may refer to my [forked repo](https://github.com/Wenzhi-Ding/pyfixest). In the forked repo, I have updated all README and Jupyter Notebook accordingly. All cells have been runned.

Basically, for frequently used functions, now it can be used like the way in `pandas`:

```python
import pyfixest as pf

data = pf.get_data()
fit1 = pf.feols("Y ~ X1 | f1 + f2", data=data).summary()

poisson_data = pf.get_data(model = "Fepois")
fit2 = pf.fepois("Y ~ X1 + X2 | f1 + f2", data = poisson_data).summary()

pf.etable([fit1, fit2])
```

For functions less used, it is now imported as
```python
from pyfixest.report import *
from pyfixest.estimation import *  # e.g., CCV, demean
from pyfixest.errors import *  # All errors/exceptions
from pyfixest.utils import *
```

or called as
```python
import pyfixest as pf

pf.estimation.demean()
pf.errors.FixedEffectInteractionError
```

I didn't change `did` modules for now.

I would like to propose three possibilities:
1. Introduce some more codes to accomodate scripts written under old version `pyfixest`.
2. Do not restructure files into sub-modules, but just simply edit the `pyfixest/__init__.py` to provide API for most frequently used functions.
3. Ignore the compatability issues, but just prompt users to update their scripts to accomodate new APIs.

I am open to either way. See what you think : )

Best regards,
Dave

**Comment by s3alfisc** [comment]
If a lot of work, we might just bite the bullet and communicate the changes very offensively, i.e. by bumping the version from 0.17 to 0.2 or even 1.0?

**Comment by Wenzhi-Ding** [comment]
> This looks very good and I'd be glad to accept the new file structure - it is clearly much cleaner than before! How much work would it be to achieve backwards compatibility (plus maybe a prompt for users to move to the new structure)?

The workload is manageable. I think it can be done within two hours. For example, called

```python
from pyfixest.summarize import table

etable()
```

This will raise a warning

```
'pyfixest.summarize.etable' is deprecated and
will be removed in a future version. Please use
'pyfixest.etable' or 'pyfixest.report.etable' instead.
You refer to https://s3alfisc.github.io/pyfixest/quickstart.html
for examples.
```

And then after a proper transition period, we can formally remove this compatibility design.

**Comment by Wenzhi-Ding** [comment]
Hi Alex,

Please see this version in my [forked repo](https://github.com/Wenzhi-Ding/pyfixest). I added backward compatibility for all functions you used in 0.16.2 documentation. So now the existing example code can run normally, with a `FutureWarning`.

[quickstart-v0.16.2](https://github.com/Wenzhi-Ding/pyfixest/blob/master/docs/quickstart-v0.16.2.ipynb)

```python
from pyfixest.summarize import summary  # import in previous way
summary(fit)
```

![image](https://github.com/s3alfisc/pyfixest/assets/30380959/88d56d1c-e279-4527-8a40-88d30be46355)

One strange thing is that, although I didn't edit any of `did` module codes, currently it fails Python 3.10 [test](https://github.com/Wenzhi-Ding/pyfixest/actions/runs/8107265611/job/22159428498). It looks like some problem in calling `rpy2`'s `did2s`.

![image](https://github.com/s3alfisc/pyfixest/assets/30380959/00fde3a4-7e43-44ab-aa85-8bc4510fcd64)

The code can pass Python 3.9/3.11/3.12 tests. Do you have any clue about what may happen?

**Comment by s3alfisc** [comment]
Hi Dave, this  looks great, thank you! Sorry for only getting to take a look at it now, I only came home a few minutes ago.

I think the github actions failure is nothing to worry about - occasionally, the workflows simply die for now good reason. I would expect your next run to not fail on 3.10 =) 

Would you open a PR? Then I'd start the formal review, merge, and publish a new version at the end of the weekend. 

Btw, I used the new etable args `keep` and `exact_match` for the first time at work today, and I had a great user experience 😄

**Comment by Wenzhi-Ding** [comment]
Thanks Alex! I have added a PR in #332.

It's great to hear those two args help : ) I also use them frequently in my papers now.
