### ISSUE TITLE
Add pre-commit to github action

### ISSUE THREAD

**Issue by juanitorduz** [s3alfisc/pyfixest#369]
I have seen you are using `ruff` (yay) you can use https://github.com/pre-commit/action to have the same pre-commit version running in the ci instead of using https://github.com/s3alfisc/pyfixest/blob/master/.github/workflows/linting.yml

**Comment by s3alfisc** [comment]
Would you maybe be up to prepare a PR for this @juanitorduz?

**Comment by s3alfisc** [comment]
@contributor-bot add @juanitorduz for infra and code
