### ISSUE TITLE
Do not use mutable objects as default arguments in Python

### ISSUE THREAD

**Issue by juanitorduz** [s3alfisc/pyfixest#371]
One should not use mutables as defaults as they can yield to unexpected behaviour, see for example https://www.reddit.com/r/Python/comments/opb7hm/do_not_use_mutable_objects_as_default_arguments/

It seems that is happening in a couple of functions, see: 

https://github.com/s3alfisc/pyfixest/blob/5fc20f81461bb21dd7312a9b9516aab38f5d753e/pyfixest/summarize.py#L13-L21

🤗

**Comment by s3alfisc** [comment]
Oh wow - that was fast! Thanks for the feedback =) This is exactly the type of Python gotcha' I had in mind when I said that "code quality could be improved here and there" =). I suppose it would be best to change all these arguments to `None` by default and initiate them within the function if they are not provided? E.g. something as 

```python
def etable(
    models: Union['Feols', 'Fepois', 'Feiv', List],
    type: Optional[str] = "md",
    signif_code: Optional[List[float]] = None,  # Set default to None
    coef_fmt: Optional[str] = "b (se)",
    custom_stats: Optional[dict] = None,  # Set default to None
    keep: Optional[Union[List, str]] = None,  # Set default to None
    drop: Optional[Union[List, str]] = None,  # Set default to None
    exact_match: Optional[bool] = False
):
    if signif_code is None:
        signif_code = [0.001, 0.01, 0.05]  # Initialize it within the function
    if custom_stats is None:
        custom_stats = {}  # Initialize it within the function
    if keep is None:
        keep = []  # Initialize it within the function
    if drop is None:
        drop = []  # Initialize it within the function
```

**Comment by juanitorduz** [comment]
For example :) I am surprised ruff did not complain about that. We can add stronger linger options. 

Also note that the Optional type is not for default parameters but when the function argument can me None, see https://stackoverflow.com/questions/51710037/how-should-i-use-the-optional-type-hint

MyPy will complain about it :)

**Comment by s3alfisc** [comment]
Yup, I just ran mypy and it complained **a lot** 😅. I'll start working on it this weekend, I have postponed this for long enough now. Thanks for the nudge, it was really needed! :)

**Comment by juanitorduz** [comment]
> Yup, I just ran mypy and it complained **a lot** 😅. I'll start working on it this weekend, I have postponed this for long enough now. Thanks for the nudge, it was really needed! :)

This is a non-trivial task and hopefully will make you improve some components of the code base, so do it bit by bit, and if you get stuck, let me know (I have fought with mypy a lot). 

My suggestion is that you add bit bit by bit in small PRs (say just add mypy to the pre-commit and should just check one file (or ignore many) and then work iteratively)

**Comment by juanitorduz** [comment]
I also recommend adding https://docs.astral.sh/ruff/rules/#flake8-bugbear-b (i.e. the rule "B") to the ruff rules list as it helps to catch these types of "errors".

**Comment by s3alfisc** [comment]
> My suggestion is that you add bit bit by bit in small PRs (say just add mypy to the pre-commit and should just check one file (or ignore many) and then work iteratively)

Yes, that was also @NKeleher's strategy when implementing the `ruff` checks =)  

> I also recommend adding https://docs.astral.sh/ruff/rules/#flake8-bugbear-b (i.e. the rule "B") to the ruff rules list as it helps to catch these types of "errors".

Yes, makes sense to me. I'll add these checks👍

**Comment by juanitorduz** [comment]
I think with the last PRs this one can be closed right :) ?

**Comment by s3alfisc** [comment]
There's one last occurrence of a mutable objects as a function argument - the internal function [demean_all ](https://github.com/s3alfisc/pyfixest/blob/e40128c5cd816a88a28d6b7b1f0cb00df4962b49/pyfixest/estimation/demean_.py#L13) still has the argument `lookup_demeaned_data`. The dictionary is used for caching demeaned variables, which is useful for speeding up regressions with multiple estimation. For example, if you run 

```python
import pyfixest as pf 
data = pf.get_data()
fit = pf.feols("Y + Y2 ~ X1 | f1", data = data)
```
`pf.feols` will first regress `Y on X1 demeaned by f1` and then `Y2 on X1 demeaned by f1`. As X1 is already demeaned in the first model, we don't have to do so again in the second model. `lookup_demeaned_data` is storing the info on demeaned data from previous regressions. 

Do you think it is ok to keep things as they are, or would you recommend a solution that does not require to pass a dict?

**Comment by juanitorduz** [comment]
> There's one last occurrence of a mutable objects as a function argument - the internal function [demean_all ](https://github.com/s3alfisc/pyfixest/blob/e40128c5cd816a88a28d6b7b1f0cb00df4962b49/pyfixest/estimation/demean_.py#L13) still has the argument `lookup_demeaned_data`. The dictionary is used for caching demeaned variables, which is useful for speeding up regressions with multiple estimation. For example, if you run
> 
> ```python
> import pyfixest as pf 
> data = pf.get_data()
> fit = pf.feols("Y + Y2 ~ X1 | f1", data = data)
> ```
> 
> `pf.feols` will first regress `Y on X1 demeaned by f1` and then `Y2 on X1 demeaned by f1`. As X1 is already demeaned in the first model, we don't have to do so again in the second model. `lookup_demeaned_data` is storing the info on demeaned data from previous regressions.
> 
> Do you think it is ok to keep things as they are, or would you recommend a solution that does not require to pass a dict?

Hey! This is actually fine! One can have mutable as function argument types! the problem is if it comes with a default value. 

So this is ok:

```python
def my_func(a: int, str: dict):
    pass
```

This is **bad**

```python
def my_func(a: int, str: dict = {}):
    pass
```

I hope it helps :) So I think we can close this one

**Comment by s3alfisc** [comment]
Ah yes, then it can indeed be closed!
