### ISSUE TITLE
`matplotlib` support for `coefplot` and `iplot`

### ISSUE THREAD

**Issue by s3alfisc** [s3alfisc/pyfixest#378]
It would be nice if both `coefplot()` and `iplot()` would support `matplotlib` as a plotting engine. Ideally, we could add a function argument named e.g. `engine` that would allow users to choose between `lets-plot` (my personal preference) and `matplotlib`, which I assume many would prefer. This would simply require changes to the `_coefplot()` function, which can be found [here](https://github.com/s3alfisc/pyfixest/blob/867643d9e69072d90aa0190b5603d66cfb56560f/pyfixest/report/visualize.py#L238).

Additionally, we could decide to make both packages optional dependencies.

@juanitorduz, would you potentially be interested to pick this up?

**Comment by juanitorduz** [comment]
Yes! I can take a look 👀 (I have never used lets_plot)

**Comment by s3alfisc** [comment]
Awesome! I really like `lets-plot` - but you have to be a fan of the grammar of graphics. Compared to `plotnine`, which I think is based on `matplotlib`, it's much faster (at least in my experience).

**Comment by juanitorduz** [comment]
@s3alfisc Here is my first proposal: Use `seaborn` objects API (https://seaborn.pydata.org/tutorial/objects_interface.html)

# Example

## Data

From the quickstart, we extract the data passed to `_coefplot`

![image](https://github.com/s3alfisc/pyfixest/assets/22996444/e93d5bc4-3268-4216-b17c-ec137491d900)

## Current Implementaton

```python
multi_fit.coefplot().show()
```

![image](https://github.com/s3alfisc/pyfixest/assets/22996444/ea775c16-587e-4814-a3d6-7a48dd3e3824)

## Proposal

This is just a first function to show the idea, we can clean the code later 

```python
import matplotlib.pyplot as plt
import seaborn.objects as so


def coefplot_matplotlib(df, **fig_kwargs):
    _, ax = plt.subplots(**fig_kwargs)
    ax.axvline(x=0, color="black", linestyle="--")

    plot = (
        so.Plot(df, x="Estimate", y="Coefficient", color="fml")
        .add(so.Dot(), so.Dodge(empty="drop"))
        .add(so.Range(), so.Dodge(empty="drop"), xmin="2.5%", xmax="97.5%")
        .label(
            title="Coefficient Plot",
            x=r"Estimate and 95% Confidence Interval",
            y="Coefficient",
            color="Model",
        )
        .on(ax)
    )
    plt.close()
    return plot


coefplot_matplotlib(df, figsize=(8, 6))
```

![image](https://github.com/s3alfisc/pyfixest/assets/22996444/2f639b5a-2d62-4063-83ac-dcf59a25fedc)

What do you think? 

P.S.  Doing this in pure matplotlib seems like an overkill as seaborns object API already has certain grammar which is more readable :)

**Comment by s3alfisc** [comment]
I think this looks great! 100% agree that `seaborn` seems like the right package for the job =) I suppose your idea would then be to rename `_coefplot()` to e.g. `_coefplot_lets_plot` and then to add a function argument to the `coefplot()` and `iplot()` functions that would allow users to choose between the two?

**Comment by juanitorduz** [comment]
exactly! That is the plan :)
