### ISSUE TITLE
Use all-contributors bot or similar tools

### ISSUE THREAD

**Issue by s3alfisc** [s3alfisc/pyfixest#383]
Use the [all-contributors bot ](https://github.com/all-contributors/all-contributors) to acknowledge contributions in the readme.

**Comment by s3alfisc** [comment]
Requires to rename the `readme.md` to `README.md`.

**Comment by s3alfisc** [comment]
@all-contributors please add @s3alfisc for code, infra

**Comment by s3alfisc** [comment]
Hi Arthur (@aeturrell), I have recently started to use the all-contributors bot to acknowledge contributors to pyfixest. In particular, all-contributions encourages to acknowledge non-code contributions, which I think is a very nice thing to do. 

Would it be ok for you if I added you to the acknowledgement section at the end of the repository for your contributions around documentation and use cases for all your help in promoting the package and in particular, adapting it in CfE? =)

**Comment by aeturrell** [comment]
I'd be honoured! That's really kind of you. So yes, of course.

**Comment by s3alfisc** [comment]
@all-contributors please add @aeturrell for tutorial, docs, promotion

**Comment by s3alfisc** [comment]
It's my pleasure, Arthur! Thanks for all your support =)
