### ISSUE TITLE
empty iplot + populate `__version__` in root `__init__.py`

### ISSUE THREAD

**Issue by apoorvalal** [s3alfisc/pyfixest#404]
Hi folks,

quick bug report I noticed when running an event study:

![image](https://github.com/s3alfisc/pyfixest/assets/12086926/0f1544e8-0dfb-424f-9244-bd7c2d74a581)

this is on the most up-to-date version of `pf` on pypi. Haven't had a chance to look at the internals that might be causing this; but I suspect it is something annoying like the coefficient matrix having unexpected names or sth.

A separate (small) issue is that I often like to check `__version__` from packages I've imported and most packages set this in the root `__init__.py` file (long discussion on where to put it [here](https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package)); this currently does not work for `pyfixest`.

**Comment by s3alfisc** [comment]
Hi @apoorvalal, thanks for reporting! This is a bug that I introduced with `0.18.0` (I believe), when I significantly reworked the string matching logic that detects the variables interacted via the "i()" operator. #405 provides a fix, I'll release to pypi once I have found the error that leads to #367. 

I'll add the `__version__` tag - this should be super useful, in particular given the frequency of new versions of pyfixest at the moment. Maybe this will also allow `watermark` to pick up pyfixest's version?

**Comment by s3alfisc** [comment]
@all-contributors please add @apoorvalal for bug.

**Comment by apoorvalal** [comment]
nice! seems like you need to add `watermark` and `autoreload` as a dependency though; the doc notebook currently has an [import error](https://github.com/s3alfisc/pyfixest/blob/master/docs/quickstart.ipynb) in the first cell

**Comment by s3alfisc** [comment]
Thanks! A fix is on the way =)
