### ISSUE TITLE
Add intro to fixed effect models sections

### ISSUE THREAD

**Issue by juanitorduz** [s3alfisc/pyfixest#435]
When looking into the quickstart (https://s3alfisc.github.io/pyfixest/quickstart.html), it seems the audience is expected to know what fixed-effect models are. I think it would be nice to have a notebook/section explaining these models and why they are useful for users who are new to the topic. This would make the documentation more accessible for a wider audience, IMO. 

Is this a contribution you would be open to having? :)

**Comment by s3alfisc** [comment]
Yes, that would be fantastic and much appreciated! I generally think that the notebooks are all a little bit too "dry", and it is indeed not optimal that they assume that every reader has taken a graduate class in econometrics =) I'd be super happy about any contribution to help in this regard!

**Comment by juanitorduz** [comment]
So would you like to add more content on the quickstart or have a separate intro notebook?

**Comment by s3alfisc** [comment]
I would be happy with both, so would be glad to follow your suggestion / preference! =)

**Comment by s3alfisc** [comment]
I will close this as we have merged #436 =)
