### ISSUE TITLE
Reproduce applied econometrics textbook examples in notebooks 

### ISSUE THREAD

**Issue by s3alfisc** [s3alfisc/pyfixest#51]
Motivation: 

- uncovers potentially needed functionality
- makes sure that pyfixest actually runs for "real world" problems and not simply my synthetic test datasets

Textbooks with code: 
- [the effect ](https://theeffectbook.net/ch-StatisticalAdjustment.html?panelset=python-code&panelset1=python-code2) (data in the causaldata package)
- [the mixtape]() (data also included in the causaldata package)
- [Data Analysis Business & Econ](https://github.com/gabors-data-analysis/da_case_studies) (github repo)

**Comment by pachadotdev** [comment]
HI!
This might be useful https://github.com/pachadotdev/tradepolicy. There I reproduced all the results from "An Advanced Guide to Trade Policy Analysis" in base R and then I did the same with fixest. The results are the same as the Stata version.

**Comment by s3alfisc** [comment]
Super cool, thanks for the pointer!
