### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by grantmcdermott** [s3alfisc/pyfixest#87]
Hey Alex,

Nice work on creating a port :-)

Any chance that you can add support for Python 3.11? It's what I have running as my default version these days and I think a lot people have already switched over b/c of the [speed gains](https://www.phoronix.com/review/python-311-performance).

Cheers.

**Comment by s3alfisc** [comment]
Hi Grant, thanks! Still a lot of work to be done here =) I have started at few attempts to resolve version conflicts to support `3.11` , but after around one hour of fruitless labor have always given up. But it's definitely on my to do list! I am currently reworking some parts of `fwildclusterboot` but will try another time after I am done there, hopefully already this weekend.

**Comment by s3alfisc** [comment]
Ah yes, I just looked at this again - the culprit was `wildboottest`, which depends on `numba`, which does not support python `3.11`. I have now made `wildboottest` optional - I think you should be able to run `pyfixest` via Python `3.11` now =)

**Comment by s3alfisc** [comment]
A new version that supports Python 3.12 is [now on Pypi ](https://pypi.org/project/pyfixest/) =) I'll have some time off in around 10 days and plan to spend some time on the package, so if you have feedback / suggestions, it'd be highly appreciated!

**Comment by grantmcdermott** [comment]
Super, thanks Alex. I just arrived in Europe on holiday, so it probably won't be soon. But I'll definitely kick the tyres when I get a chance. 

P.S. Thanks too for the wild cluster bootstrap discussion over at my etwfe repo. That's also on the backburner until I get over jetlag etc. ;-)

**Comment by s3alfisc** [comment]
Great, I hope you'll have a great time over here! And if all goes well, `fwildclusterboot` might support `etwfe` by the time you are back =)
